run_name = "epem_a_ttxh@LO"
output_dir = "epem_a_ttxh/LO"
templates = [
    "settings/templates/flow/size7",
    "settings/templates/madnis_bins/size2",
    "settings/templates/transformer/size4",
]

[gammaloop]
state = "epem_a_ttxh/LO/state"
integration_workspace = "examples/cli/epem_a_ttxh/LO/state/integration_workspace"
integrand_name = "LO"

[integrator.madnis]
batch_size = 10000
learning_rate = 1e-3
use_scheduler = true
scheduler_type = "cosineannealing"

[integrator.havana]
max_prob_ratio = 10

[layered_integrand]
integrand_type = "gammaloop"
training_phase = "imag"
n_cores = 64

[integrand.gammaloop]
process_id = 0
integrand_name = "LO"
momentum_space = false
sample_lmbs = true
sample_orientations = false
use_arb_prec = false
minimal_output = true
read_only_state = true

[scripts.sampler_comp]
n_training_steps = 1000
n_samples = 1_000_000
n_samples_after_training = 10_000_000
