run_name = "epem_a_ttxh@LO_semi_inclusive"
output_dir = "epem_a_ttxh/LO_semi_inclusive"
templates = [
    "settings/epem_a_ttxh/epem_a_ttxh_LO",
    "settings/templates/flow/size7",
    "settings/templates/madnis_bins/size2",
    "settings/templates/transformer/size4",
]

[layered_integrand]
integrand_type = "gammaloop"
training_phase = "real"
n_cores = 64

[integrand.gammaloop]
integrand_name = "LO_semi_inclusive"

[[scripts.slice_plots.slice]]
origin = [0.21197481, 0.50832561, 0.72426355, 0.28365847, 0.96061689, 0.16644217]
discrete = [0]
dirs = [0, 3]
grid = [
    {start = 0, stop = 1, num = 1000},
    {start = 0, stop = 1, num = 1000},
]
[[scripts.slice_plots.slice]]
origin = [0.21197481, 0.50832561, 0.72426355, 0.28365847, 0.96061689, 0.16644217]
discrete = [1]
dirs = [0, 3]
grid = [
    {start = 0, stop = 1, num = 1000},
    {start = 0, stop = 1, num = 1000},
]
