run_name = "bugblatter_t070_optimised_v2"
templates = [
    "settings/vacuum_graphs/bugblatter/bugblatter_t070_base",
    "settings/templates/flow/size9",
    "settings/templates/transformer/size3",
]

[integrator.madnis]
# loss_type = "variance"
loss_type = "kl_divergence"
scheduler_type = "cosineannealing"
batch_size = 20_000
learning_rate = 1e-3

[integrator.madnis.flow_kwargs]
bins = 10
min_bin_width = 2e-2
min_bin_height = 1e-4
min_bin_derivative = 1e-6
uniform_latent = true
permutations = "log"
layers = 4
units = 1600

[layered_parameterisation.layer_0]
parameterisation_type = "rkaapo"
mu = [1.0, 1.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0]
a = 0.55
b = 1.0

[layered_parameterisation.layer_1]
parameterisation_type = "mc_layer"
subtype = "fermi"
ose_exponent = 6.0
fermi_exponent = 1.0

[scripts.training_prog]
n_training_steps = 2000
n_samples = 1000000
n_samples_after_training = 100000000
n_log = 20
n_plot_snapshot = 100
n_plot_loss = 10
