run_name = "bugblatter_t030"
templates = [
    "settings/vacuum_graphs/bugblatter/bugblatter",
    "settings/vacuum_graphs/bugblatter/bugblatter_tseries"
]

[integration_target]
n_points = 416000000
real_mean = -0.00000688441782011863
real_error = 0.0000000200846984630986

[layered_integrand]
params = [0.190270777045349, 1.0, 33.0223348259205]

[scripts.slice_plots]
slice_dims_2d = [[4, 5]]
