run_name = "bugblatter_t140"
templates = [
    "settings/vacuum_graphs/bugblatter/bugblatter",
    "settings/vacuum_graphs/bugblatter/bugblatter_tseries"
]

[integration_target]
n_points = 290000000
real_central_value = 0.00000284519002379118
real_error = 0.0000000199447762054874

[layered_integrand]
params = [1.13987741624273, 1.0, 5.5121587792223]

[scripts.slice_plots]
slice_dims_2d = [[4, 5]]
