run_name = "bugblatter_t070"
templates = [
    "settings/vacuum_graphs/bugblatter/bugblatter",
    "settings/vacuum_graphs/bugblatter/bugblatter_tseries"
]

[integration_target]
n_points = 290000000
real_central_value = -0.00000624159212391007
real_error = 0.0000000179007098142485

[layered_integrand]
params = [0.46390258023886, 1.0, 13.5441913341902]

[scripts.training_prog]
n_samples_after_training = 290000000
