run_name = "bugblatter_t070_pretrained"
templates = [
    "settings/vacuum_graphs/bugblatter/bugblatter",
    "settings/vacuum_graphs/bugblatter/bugblatter_tseries",
    "settings/vacuum_graphs/bugblatter/bugblatter_t070",
    "settings/vacuum_graphs/bugblatter/bugblatter_optimised",
]

[layered_integrator]
pretrain_c_flow = true

[integrator.madnis.pretraining_kwargs]
nitn=10
neval=1000000
bins_mult=20
alpha=0.3