run_name = "bugblatter_hpcomp"
templates = [
    "settings/vacuum_graphs/bugblatter/bugblatter_t070_base",
    "settings/templates/flow/size5",
    "settings/templates/madnis_bins/size3",
    "settings/templates/transformer/size3",
]

name[[scripts.hyperparam_comparison.comparison]]
name = "bins"
blocks = [
        ["settings/templates/madnis_bins/size0"],
        ["settings/templates/madnis_bins/size1"],
        ["settings/templates/madnis_bins/size2"],
        ["settings/templates/madnis_bins/size3"],
        ["settings/templates/madnis_bins/size4"],
    ]
block_names = [5, 10, 20, 50, 100]

name[[scripts.hyperparam_comparison.comparison]]
name = "flow network"
blocks = [
        ["settings/templates/flow/size5"],
        ["settings/templates/flow/size6"],
        ["settings/templates/flow/size7"],
        ["settings/templates/flow/size8"],
        ["settings/templates/flow/size9"],
    ]
block_names = ["3_256", "4_256", "4_512", "5_512", "5_1024"]

name[[scripts.hyperparam_comparison.comparison]]
name = "transformer network"
blocks = [
        ["settings/templates/transformer/size0"],
        ["settings/templates/transformer/size1"],
        ["settings/templates/transformer/size2"],
        ["settings/templates/transformer/size3"],
        ["settings/templates/transformer/size4"],
    ]
block_names = ["1_1_1_32", "1_2_2_32", "2_2_2_64", "2_3_3_64", "4_3_3_64"]

name[[scripts.hyperparam_comparison.comparison]]
name = "made network"
blocks = [
        ["settings/templates/made/size2"],
        ["settings/templates/made/size3"],
        ["settings/templates/made/size4"],
    ]
block_names = ["2_8", "2_16", "3_16"]

name[[scripts.hyperparam_comparison.comparison]]
name = "big flow bins"
blocks = [
        [
            "settings/templates/flow/size9",
            "settings/templates/madnis_bins/size0",
        ],
        [
            "settings/templates/flow/size9",
            "settings/templates/madnis_bins/size1",
        ],
        [
            "settings/templates/flow/size9",
            "settings/templates/madnis_bins/size2",
        ],
        [
            "settings/templates/flow/size9",
            "settings/templates/madnis_bins/size3",
        ],
        [
            "settings/templates/flow/size9",
            "settings/templates/madnis_bins/size4",
        ],
    ]
block_names = ["5_1024_5", "5_1024_10", "5_1024_20", "5_1024_50", "5_1024_100"]

[scripts.hpcomp_training_run]
n_training_steps = 1000
n_samples = 1000000
n_samples_after_training = 10000000
n_log = 20
n_plot_snapshot = 100
n_plot_loss = 2
