run_name = "epem_a_tth@NLO"
output_dir = "epem_a_tth/NLO/GL08"
templates = [
    "settings/templates/flow/size9",
    "settings/templates/madnis_bins/size1",
    "settings/templates/transformer/size4",
    "settings/templates/parameterisation/mc_lmb_spherical_no_heur",
]

[gammaloop]
state = "epem_a_ttxh/NLO/GL08/state"
integration_workspace = "epem_a_ttxh/NLO/GL08/state/integration_workspace"
get_target_from_gammaloop = true
prefer_gammaloop_over_target = true

[integration_target]
imag_mean = -3.2336e-06

[integrator.madnis]
batch_size = 20000
learning_rate = 4e-4

[layered_integrand]
integrand_type = "gammaloop"
training_phase = "imag"
n_cores = 128

[integrand.gammaloop]
momentum_space = false
sample_lmbs = "summed"
sample_orientations = false
integrand_name = "NLO"

[scripts.sampler_comp]
n_training_steps = 1000
n_samples = 100000
n_samples_after_training = 10000000

[[scripts.hyperparam_comparison.comparison]]
name = "gl_param"
blocks = [
    [
        """
        [integrand.gammaloop]
        momentum_space = true
        sample_lmbs = false
        sample_orientations = false
        integrand_name = "NLO"
        """,
        "settings/templates/parameterisation/mc_lmb_spherical_no_heur",
    ],
    [
        """
        [integrand.gammaloop]
        momentum_space = true
        sample_lmbs = "summed"
        sample_orientations = false
        integrand_name = "NLO"
        """,
        "settings/templates/parameterisation/mc_lmb_spherical",
    ],
    [
        """
        [integrand.gammaloop]
        momentum_space = true
        sample_lmbs = false
        sample_orientations = true
        integrand_name = "NLO"
        """,
        "settings/templates/parameterisation/mc_lmb_spherical_no_heur",
    ],
    [
        """
        [integrand.gammaloop]
        momentum_space = true
        sample_lmbs = "summed"
        sample_orientations = true
        integrand_name = "NLO"
        """,
        "settings/templates/parameterisation/mc_lmb_spherical",
    ],
]
block_names = ["no_heur", "heur", "no_heur_orientations", "heur_orientations"]
[[scripts.hyperparam_comparison.comparison]]
name = "gl"
blocks = [
    [
        """
        [integrand.gammaloop]
        momentum_space = false
        sample_lmbs = "summed"
        sample_orientations = false
        integrand_name = "NLO"
        """,
    ],
    [
        """
        [integrand.gammaloop]
        momentum_space = false
        sample_lmbs = "summed"
        sample_orientations = true
        integrand_name = "NLO"
        """,
    ],
    [
        """
        [integrand.gammaloop]
        momentum_space = true
        sample_lmbs = false
        sample_orientations = true
        integrand_name = "NLO"
        """,
    ],
]
block_names = ["smlmb", "smlmb+or", "nolmb+or", ]

[scripts.hpcomp_training_run]
n_training_steps = 2000
n_samples = 1_000_000
n_samples_after_training = 10_000_000
n_log = 50
n_plot_snapshot = 200
n_plot_loss = 10
plot_disc = true
n_plot_disc = 2
