run_name = "gg_hhh_1L"

[graph]
momtrop_edge_weight = 0.555555555555

[gammaloop_state]
state_dir = "/home/nfink/gammaloop"
state_name = "GL_OUTPUT/gg_hhh/1L/state"
integration_state_name = "GL_OUTPUT/gg_hhh/1L/integration_workspace"

[integrator.madnis]
batch_size = 2000
discrete_model = "transformer"

[integrator.madnis.transformer]
embedding_dim = 128
feedforward_dim = 256
heads = 2
mlp_units = 128
transformer_layers = 2

[layered_parameterisation.layer_0]
parameterisation_type = "spherical"
conformal_scale = 1.0

[layered_parameterisation.layer_1]
parameterisation_type = "mc_layer"
subtype = "ose"
ose_exponent = 1.0

[layered_integrand]
integrand_type = "gammaloop"
training_phase = "real"
n_cores = 128

[scripts.sampler_comp]
n_training_steps = 500
n_samples = 100000
n_samples_after_training = 1000000
