run_name = "gg_hhh_1L"
templates = [
    "settings/templates/flow/size6",
    "settings/templates/madnis_bins/size1",
    "settings/templates/transformer/size2",
]

[gammaloop_state]
state_dir = "/home/nfink/gammaloop"
state_name = "GL_OUTPUT/gg_hhh/1L/state/state"
integration_state_name = "GL_OUTPUT/gg_hhh/1L/state/integration_workspace"
integration_result_file = "integration_result.json"

[integrator.madnis]
batch_size = 10000
learning_rate = 1e-3
use_scheduler = true
scheduler_type = "cosineannealing"

[layered_parameterisation.layer_0]
parameterisation_type = "spherical"
conformal_scale = 0.0

[layered_parameterisation.layer_1]
parameterisation_type = "mc_layer"
subtype = "ose"
ose_exponent = 1.0

[layered_integrand]
integrand_type = "gammaloop"
training_phase = "imag"
n_cores = 16

[scripts.sampler_comp]
n_training_steps = 1000
n_samples = 1000000
n_samples_after_training = 10000000
