run_name = "test_nomc"

[graph]
from_state = false
momtrop_edge_weight = 0.75
is_vacuum = true
overwrite_graph_properties = true

[integration_target]
real_central_value = 1.0

[graph.graph_properties]
edge_src_dst_vertices = [
    [0, 1], 
    [1, 0], 
    [1, 0]
]
edge_masses = [
    0.0,
    0.0,
    0.0
]
edge_momentum_shifts = [
    [
        0.0,
        0.0,
        0.0
    ],
    [
        0.0,
        0.0,
        0.0
    ],
    [
        0.0,
        0.0,
        0.0
    ]
]
graph_external_vertices = []
graph_signature = [
    [1, 0], 
    [0, 1], 
    [1, -1]
]
momtrop_edge_weight = []
lmb_array = [
    [0, 1], 
    [0, 2], 
    [1, 2]
]
[model]
from_state = false

[layered_integrator]
integrator_type = "madnis"
batch_size = 1000
learning_rate = 1e-3
use_scheduler = true
discrete_model = "transformer"

[integrator.madnis.transformer]
embedding_dim  = 64
feedforward_dim = 256
heads = 8
transformer_layers = 3
mlp_layers = 3
mlp_units = 256

[layered_parameterisation.layer_0]
parameterisation_type = "spherical"

[layered_integrand]
integrand_type = "test"
n_cores = 1

# Parameters used in the tprog subcommand
[scripts.sampler_comp]
n_training_steps = 50
n_samples = 1000
nitn = 5
# Number of samples drawn after the training to compute the final result
n_samples_after_training = 10000
# Training steps between callback of loss to console
n_log = 1
# Training steps between drawing n_samples samples to calculate the rel. std. (rsd)
# Will also output the result +- error and rsd to console
n_plot_rsd = 5
# Training steps between plotting the loss
n_plot_loss = 1

[scripts.training_prog]
n_training_steps = 50
n_samples = 1000
n_samples_after_training = 20000
n_log = 1
n_plot_rsd = 5
n_plot_loss = 1

[scripts.slice_plots]
n_samples_1d = 1000
n_samples_2d = 100
