run_name = "test_hpcomp"
templates = [
    "settings/templates/flow/size1",
    "settings/templates/madnis_bins/size1",
    "settings/templates/transformer/size1",
    ]

[graph]
from_state = false
momtrop_edge_weight = 0.75
is_vacuum = true
overwrite_graph_properties = true

[integration_target]
real_central_value = 1.0

[graph.graph_properties]
edge_src_dst_vertices = [
    [0, 1], 
    [1, 0], 
    [1, 0]
]
edge_masses = [
    0.0,
    0.0,
    0.0
]
edge_momentum_shifts = [
    [
        0.0,
        0.0,
        0.0
    ],
    [
        0.0,
        0.0,
        0.0
    ],
    [
        0.0,
        0.0,
        0.0
    ]
]
graph_external_vertices = []
graph_signature = [
    [1, 0], 
    [0, 1], 
    [1, -1]
]
momtrop_edge_weight = []
lmb_array = [
    [0, 1], 
    [0, 2], 
    [1, 2]
]
[model]
from_state = false

[layered_integrator]
integrator_type = "madnis"

[integrator.madnis]
batch_size = 1000
learning_rate = 1e-3
use_scheduler = true
pretrain_c_flow = false

[layered_integrand]
integrand_type = "test"
n_cores = 1

[layered_parameterisation.layer_0]
parameterisation_type = "spherical"

[layered_parameterisation.layer_1]
parameterisation_type = "mc_layer"
subtype = "ose"
ose_exponent = 1
fermi_exponent = 0.5

[[scripts.hyperparam_comparison]]
comparison_name = "bins"
blocks = [
        ["settings/templates/madnis_bins/size0"],
        ["settings/templates/madnis_bins/size1"],
        ["settings/templates/madnis_bins/size2"],
    ]
block_names = [5, 10, 20]

[[scripts.hyperparam_comparison]]
comparison_name = "flow network"
blocks = [
        ["settings/templates/flow/size0"],
        ["settings/templates/flow/size1"],
        ["settings/templates/flow/size2"],
        ["settings/templates/flow/size3"],
    ]
block_names = ["1_16", "1_64", "2_64", "2_128"]

[[scripts.hyperparam_comparison]]
comparison_name = "transformer network"
blocks = [
        ["settings/templates/transformer/size0"],
        ["settings/templates/transformer/size1"],
        ["settings/templates/transformer/size2"],
    ]
block_names = ["1_1_1_32", "1_2_2_32", "2_2_2_64",]

[[scripts.hyperparam_comparison]]
comparison_name = "made network"
blocks = [
        ["settings/templates/made/size0"],
        ["settings/templates/made/size1"],
        ["settings/templates/made/size2"],
    ]
block_names = ["1_4", "1_8", "2_8",]

[scripts.hpcomp_training_run]
n_training_steps = 30
n_samples = 1000
n_samples_after_training = 20000
n_log = 5
n_plot_rsd = 10
n_plot_loss = 1
