run_name = "gg_hhh@1L xspace"
output_dir = "gg_hhh/1L/xspace"
templates = [
    "settings/gg_hhh/gg_hhh_1L",
    "settings/templates/flow/size6",
    "settings/templates/madnis_bins/size1",
    "settings/templates/transformer/size2",
]

[integrand.gammaloop]
momentum_space = false
sample_lmbs = true
sample_orientations = false

[[scripts.slice_plots.slice]]
origin = [0.58196708, 0.18319655, 0.95370665]
dirs = [0, 1]
grid = [
    {start = 0, stop = 1, num = 1000},
    {start = 0, stop = 1, num = 1000},
]
[[scripts.slice_plots.slice]]
origin = [0.58196708, 0.18319655, 0.95370665]
dirs = [0, 2]
grid = [
    {start = 0, stop = 1, num = 1000},
    {start = 0, stop = 1, num = 1000},
]
[[scripts.slice_plots.slice]]
origin = [0.58196708, 0.18319655, 0.95370665]
dirs = [1, 2]
grid = [
    {start = 0, stop = 1, num = 1000},
    {start = 0, stop = 1, num = 1000},
]