run_name = "mercedes_hpcomp"
templates = [
    "settings/vacuum_graphs/mercedes/mercedes_base",
    "settings/templates/flow/size2",
    "settings/templates/madnis_bins/size2",
    "settings/templates/transformer/size2",
]

[[scripts.hyperparam_comparison]]
comparison_name = "bins"
blocks = [
        ["settings/templates/madnis_bins/size0"],
        ["settings/templates/madnis_bins/size1"],
        ["settings/templates/madnis_bins/size2"],
        ["settings/templates/madnis_bins/size3"],
        ["settings/templates/madnis_bins/size4"],
        ["settings/templates/madnis_bins/size5"],
    ]
block_names = [5, 10, 20, 50, 100, 200]

[[scripts.hyperparam_comparison]]
comparison_name = "flow network"
blocks = [
        ["settings/templates/flow/size0"],
        ["settings/templates/flow/size1"],
        ["settings/templates/flow/size2"],
        ["settings/templates/flow/size3"],
        ["settings/templates/flow/size4"],
        ["settings/templates/flow/size5"],
        ["settings/templates/flow/size6"],
        ["settings/templates/flow/size7"],
        ["settings/templates/flow/size8"],
        ["settings/templates/flow/size9"],
    ]
block_names = ["1_16", "1_64", "2_64", "2_128", "3_128", "3_256", "4_256", "4_512", "5_512", "5_1024"]

[[scripts.hyperparam_comparison]]
comparison_name = "transformer network"
blocks = [
        ["settings/templates/transformer/size0"],
        ["settings/templates/transformer/size1"],
        ["settings/templates/transformer/size2"],
        ["settings/templates/transformer/size3"],
        ["settings/templates/transformer/size4"],
        ["settings/templates/transformer/size5"],
    ]
block_names = ["1_1_1_32", "1_2_2_32", "2_2_2_64", "2_3_3_64", "4_3_3_64", "8_3_3_128"]

[[scripts.hyperparam_comparison]]
comparison_name = "made network"
blocks = [
        ["settings/templates/made/size0"],
        ["settings/templates/made/size1"],
        ["settings/templates/made/size2"],
        ["settings/templates/made/size3"],
        ["settings/templates/made/size4"],
        ["settings/templates/made/size5"],
    ]
block_names = ["1_4", "1_8", "2_8", "2_16", "3_16", "3_32"]

[[scripts.hyperparam_comparison]]
comparison_name = "big flow bins"
blocks = [
        [
            "settings/templates/flow/size9",
            "settings/templates/bins/size0",
        ],
        [
            "settings/templates/flow/size9",
            "settings/templates/bins/size1",
        ],
        [
            "settings/templates/flow/size9",
            "settings/templates/bins/size2",
        ],
        [
            "settings/templates/flow/size9",
            "settings/templates/bins/size3",
        ],
        [
            "settings/templates/flow/size9",
            "settings/templates/bins/size4",
        ],
    ]
block_names = ["5_1024_20", "5_1024_50", "5_1024_100"]

[scripts.hpcomp_training_run]
n_training_steps = 1000
n_samples = 1000000
n_samples_after_training = 10000000
n_log = 20
n_plot_rsd = 100
n_plot_loss = 2
