run_name = "mercedes_optimised_nos"
templates = [
    "settings/vacuum_graphs/mercedes/mercedes_base",
    "settings/templates/flow/size9",
    "settings/templates/madnis_bins/size1",
    "settings/templates/transformer/size3",
]

[layered_parameterisation.layer_0]
parameterisation_type = "rkaapo"
# chem potential [3.141592653589793, 3.141592653589793, 3.141592653589793, 0.0, 0.0, 0.0]
# no chem potential [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
mu = [3.141592653589793, 3.141592653589793, 3.141592653589793, 0.0, 0.0, 0.0]
a = 0.6
b = 1.0

[layered_parameterisation.layer_1]
parameterisation_type = "mc_layer"
subtype = "fermi"
ose_exponent = 5.0
fermi_exponent = 0.5

[layered_integrand]
integrand_type = "kaapo"
path_to_example = "thermal_integrand_examples/mercedes"
# chem potential [6.283185307179586, 3.141592653589793, 1.0]
# no chem potential [6.283185307179586, 0.0, 1.0] 
params = [6.283185307179586, 3.141592653589793, 1.0]
use_prec = true
use_f128 = true
n_cores = 128
# chem potential 0.0290399
# no chem potential 0.714390
target_real = 0.0290399

[integrand.kaapo.symbolica_integrand_kwargs]
rotation_seed = 42
stability_tolerance = 1e-5
stability_abs_threshold = 1e-12
stability_abs_tolerance = 1e-15
escalate_large_weight_multiplier = 0.9
escalate_small_momentum_multiplier = 1e-3
escalate_large_momentum_multiplier = 1e3
n_shots = 3
force_rebuild = false
sum_orientations = true
runtime_summation = false

[integrand.kaapo.symbolica_integrand_prec_kwargs]
prec = 200
n_shots = 1
escalate_large_weight_multiplier = -1.0
escalate_small_momentum_multiplier = -1.0
escalate_large_momentum_multiplier = -1.0
sum_orientations = true
runtime_summation = false

[scripts.sampler_comp]
n_training_steps = 2000
n_samples = 100000
n_samples_after_training = 10000000
n_log = 20
n_plot_snapshot = 100
n_plot_loss = 2
n_itn = 10
plot_disc = true
n_plot_disc = 2

[[scripts.slice_plots.slice]]
origin = [0.99851443, 0.67706214, 0.37406779, 0.99876717, 0.47234072, 0.91826003]
discrete = [4]
dirs = [0, 1]
grid = [
    {start = 0, stop = 1, num = 1000},
    {start = 0, stop = 1, num = 1000},
]
[[scripts.slice_plots.slice]]
origin = [0.99851443, 0.67706214, 0.37406779, 0.99876717, 0.47234072, 0.91826003]
discrete = [4]
dirs = [0, 2]
grid = [
    {start = 0, stop = 1, num = 1000},
    {start = 0, stop = 1, num = 1000},
]
[[scripts.slice_plots.slice]]
origin = [0.99851443, 0.67706214, 0.37406779, 0.99876717, 0.47234072, 0.91826003]
discrete = [4]
dirs = [1, 2]
grid = [
    {start = 0, stop = 1, num = 1000},
    {start = 0, stop = 1, num = 1000},
]
[[scripts.slice_plots.slice]]
origin = [0.97218279, 0.95071461, 0.30111655, 0.92599541, 0.01998822, 0.27606145]
discrete = [5]
dirs = [0, 1]
grid = [
    {start = 0, stop = 1, num = 1000},
    {start = 0, stop = 1, num = 1000},
]
[[scripts.slice_plots.slice]]
origin = [0.97218279, 0.95071461, 0.30111655, 0.92599541, 0.01998822, 0.27606145]
discrete = [5]
dirs = [0, 2]
grid = [
    {start = 0, stop = 1, num = 1000},
    {start = 0, stop = 1, num = 1000},
]
[[scripts.slice_plots.slice]]
origin = [0.97218279, 0.95071461, 0.30111655, 0.92599541, 0.01998822, 0.27606145]
discrete = [5]
dirs = [1, 2]
grid = [
    {start = 0, stop = 1, num = 1000},
    {start = 0, stop = 1, num = 1000},
]
