run_name = "mercedes_optimised"
templates = [
    "settings/vacuum_graphs/mercedes/mercedes_base",
    "settings/vacuum_graphs/mercedes/mercedes_optimised",
    "settings/templates/flow/size9",
    "settings/templates/madnis_bins/size1",
    "settings/templates/transformer/size3",
]

[layered_integrand]
sum_channels = true
