run_name = "mercedes_hpcomp"
templates = [
    "settings/vacuum_graphs/mercedes/mercedes_base",
    "settings/templates/flow/size7",
    "settings/templates/madnis_bins/size1",
    "settings/templates/transformer/size3",
]

[[scripts.hyperparam_comparison.comparison]]
name = "bins"
plot_slices = true
blocks = [
        ["settings/templates/madnis_bins/size0"],
        ["settings/templates/madnis_bins/size1"],
        ["settings/templates/madnis_bins/size2"],
        ["settings/templates/madnis_bins/size3"],
        ["settings/templates/madnis_bins/size4"],
    ]
block_names = [5, 10, 20, 50, 100]

[[scripts.hyperparam_comparison.comparison]]
name = "flow network"
plot_slices = true
blocks = [
        ["settings/templates/flow/size2"],
        ["settings/templates/flow/size3"],
        ["settings/templates/flow/size4"],
        ["settings/templates/flow/size5"],
        ["settings/templates/flow/size6"],
        ["settings/templates/flow/size7"],
        ["settings/templates/flow/size8"],
        ["settings/templates/flow/size9"],
    ]
block_names = ["2_64", "2_128", "3_128", "3_256", "4_256", "4_512", "5_512", "5_1024"]

[[scripts.hyperparam_comparison.comparison]]
name = "transformer network"
plot_slices = true
blocks = [
        ["settings/templates/transformer/size0"],
        ["settings/templates/transformer/size1"],
        ["settings/templates/transformer/size2"],
        ["settings/templates/transformer/size3"],
        ["settings/templates/transformer/size4"],
        ["settings/templates/transformer/size5"],
    ]
block_names = ["1_1_1_32", "1_2_2_32", "2_2_2_64", "2_3_3_64", "4_3_3_64", "8_3_3_128"]

[[scripts.hyperparam_comparison.comparison]]
name = "made network"
plot_slices = true
blocks = [
        ["settings/templates/made/size0"],
        ["settings/templates/made/size1"],
        ["settings/templates/made/size2"],
        ["settings/templates/made/size3"],
        ["settings/templates/made/size4"],
        ["settings/templates/made/size5"],
    ]
block_names = ["1_4", "1_8", "2_8", "2_16", "3_16", "3_32"]

[[scripts.hyperparam_comparison.comparison]]
name = "big flow bins"
plot_slices = true
blocks = [
        [
            "settings/templates/flow/size9",
            "settings/templates/madnis_bins/size0",
        ],
        [
            "settings/templates/flow/size9",
            "settings/templates/madnis_bins/size1",
        ],
        [
            "settings/templates/flow/size9",
            "settings/templates/madnis_bins/size2",
        ],
        [
            "settings/templates/flow/size9",
            "settings/templates/madnis_bins/size3",
        ],
        [
            "settings/templates/flow/size9",
            "settings/templates/madnis_bins/size4",
        ],
    ]
block_names = ["5_1024_5", "5_1024_10", "5_1024_20", "5_1024_50", "5_1024_100"]

[[scripts.hyperparam_comparison.comparison]]
name = "fermi_mc"
plot_slices = true
blocks = [
        ["settings/templates/flow/size7",
        """
        [layered_parameterisation.layer_0]
        a = 1.0
        [layered_parameterisation.layer_1]
        fermi_exponent = 1.0
        """],
        ["settings/templates/flow/size7",
        """
        [layered_parameterisation.layer_0]
        a = 0.5
        [layered_parameterisation.layer_1]
        fermi_exponent = 1.0
        """],
        ["settings/templates/flow/size7",
        """
        [layered_parameterisation.layer_0]
        a = 1.0
        [layered_parameterisation.layer_1]
        fermi_exponent = 0.7
        """],
        ["settings/templates/flow/size7",
        """
        [layered_parameterisation.layer_0]
        a = 0.5
        [layered_parameterisation.layer_1]
        fermi_exponent = 0.7
        """],
        ["settings/templates/flow/size7",
        """
        [layered_parameterisation.layer_0]
        a = 1.0
        [layered_parameterisation.layer_1]
        fermi_exponent = 0.3
        """],
        ["settings/templates/flow/size7",
        """
        [layered_parameterisation.layer_0]
        a = 0.5
        [layered_parameterisation.layer_1]
        fermi_exponent = 0.3
        """],
    ]
block_names = [
    "1.0_1.0", "0.5_1.0", "1.0_0.7", "0.5_0.7", 
    "1.0_0.3", "0.5_0.3", 
]

[[scripts.hyperparam_comparison.comparison]]
name = "ose_mc"
plot_slices = true
blocks = [
        ["settings/templates/flow/size7",
        """
        [layered_parameterisation.layer_0]
        a = 1.0
        [layered_parameterisation.layer_1]
        subtype = "ose"
        ose_exponent = 2.0
        """],
        ["settings/templates/flow/size7",
        """
        [layered_parameterisation.layer_0]
        a = 0.5
        [layered_parameterisation.layer_1]
        ose_exponent = 2.0
        """],
        ["settings/templates/flow/size7",
        """
        [layered_parameterisation.layer_0]
        a = 1.0
        [layered_parameterisation.layer_1]
        subtype = "ose"
        ose_exponent = 4.0
        """],
        ["settings/templates/flow/size7",
        """
        [layered_parameterisation.layer_0]
        a = 0.5
        [layered_parameterisation.layer_1]
        ose_exponent = 4.0
        """],
        ["settings/templates/flow/size7",
        """
        [layered_parameterisation.layer_0]
        a = 1.0
        [layered_parameterisation.layer_1]
        subtype = "ose"
        ose_exponent = 6.0
        """],
        ["settings/templates/flow/size7",
        """
        [layered_parameterisation.layer_0]
        a = 0.5
        [layered_parameterisation.layer_1]
        ose_exponent = 6.0
        """],
        ["settings/templates/flow/size7",
        """
        [layered_parameterisation.layer_0]
        a = 1.0
        [layered_parameterisation.layer_1]
        subtype = "ose"
        ose_exponent = 8.0
        """],
        ["settings/templates/flow/size7",
        """
        [layered_parameterisation.layer_0]
        a = 0.5
        [layered_parameterisation.layer_1]
        ose_exponent = 8.0
        """],
    ]
block_names = [
    "1.0_2.0", "0.5_2.0", "1.0_4.0", "0.5_4.0", 
    "1.0_6.0", "0.5_6.0", "1.0_8.0", "0.5_8.0",
]

[scripts.hpcomp_training_run]
n_training_steps = 1000
n_samples = 1000000
n_samples_after_training = 10000000
n_log = 50
n_plot_snapshot = 100
n_plot_loss = 2
plot_disc = true
n_plot_disc = 2

[[scripts.hpcomp_slice_plots.slice]]
origin = [0.99851443, 0.67706214, 0.37406779, 0.99876717, 0.47234072, 0.91826003]
discrete = [4]
dirs = [0, 1]
grid = [
    {start = 0, stop = 1, num = 1000},
    {start = 0, stop = 1, num = 1000},
]
[[scripts.hpcomp_slice_plots.slice]]
origin = [0.97218279, 0.95071461, 0.30111655, 0.92599541, 0.01998822, 0.27606145]
discrete = [5]
dirs = [0, 1]
grid = [
    {start = 0, stop = 1, num = 1000},
    {start = 0, stop = 1, num = 1000},
]

[scripts.sampler_comp]
n_training_steps = 1000
n_samples = 1000000
n_samples_after_training = 10000000
n_log = 20
n_plot_snapshot = 100
n_plot_loss = 2
plot_disc = true
n_plot_disc = 2

[[scripts.slice_plots.slice]]
origin = [0.99851443, 0.67706214, 0.37406779, 0.99876717, 0.47234072, 0.91826003]
discrete = [4]
dirs = [0, 1]
grid = [
    {start = 0, stop = 1, num = 1000},
    {start = 0, stop = 1, num = 1000},
]
[[scripts.slice_plots.slice]]
origin = [0.99851443, 0.67706214, 0.37406779, 0.99876717, 0.47234072, 0.91826003]
discrete = [4]
dirs = [0, 2]
grid = [
    {start = 0, stop = 1, num = 1000},
    {start = 0, stop = 1, num = 1000},
]
[[scripts.slice_plots.slice]]
origin = [0.99851443, 0.67706214, 0.37406779, 0.99876717, 0.47234072, 0.91826003]
discrete = [4]
dirs = [1, 2]
grid = [
    {start = 0, stop = 1, num = 1000},
    {start = 0, stop = 1, num = 1000},
]
[[scripts.slice_plots.slice]]
origin = [0.97218279, 0.95071461, 0.30111655, 0.92599541, 0.01998822, 0.27606145]
discrete = [5]
dirs = [0, 1]
grid = [
    {start = 0, stop = 1, num = 1000},
    {start = 0, stop = 1, num = 1000},
]
[[scripts.slice_plots.slice]]
origin = [0.97218279, 0.95071461, 0.30111655, 0.92599541, 0.01998822, 0.27606145]
discrete = [5]
dirs = [0, 2]
grid = [
    {start = 0, stop = 1, num = 1000},
    {start = 0, stop = 1, num = 1000},
]
[[scripts.slice_plots.slice]]
origin = [0.97218279, 0.95071461, 0.30111655, 0.92599541, 0.01998822, 0.27606145]
discrete = [5]
dirs = [1, 2]
grid = [
    {start = 0, stop = 1, num = 1000},
    {start = 0, stop = 1, num = 1000},
]
