run_name = "scalar@2p4L"
output_dir = "scalar/2p4L"
templates = [
    "settings/templates/flow/size9",
    "settings/templates/madnis_bins/size1",
    "settings/templates/transformer/size4",
]

[graph]
momtrop_edge_weight = 0.7777777777777

[gammaloop]
state = "scalar/2p4L/state"
integration_workspace = "scalar/2p4L/state/integration_workspace"
get_target_from_gammaloop = true

[layered_integrator]
integrator_type = "madnis"

[integrator.madnis]
batch_size = 16384
learning_rate = 4e-4

[layered_integrand]
integrand_type = "gammaloop"
training_phase = "real"
n_cores = 32
use_f128 = true

[scripts.sampler_comp]
n_training_steps = 500
n_samples = 100000
n_samples_after_training = 1000000
