run_name = "scalar@2p3L"
output_dir = "scalar/2p3L"
templates = [
    "settings/scalar/base",
    "settings/templates/flow/size7",
    "settings/templates/madnis_bins/size1",
    "settings/templates/transformer/size4",
]

[graph]
momtrop_edge_weight = 0.78571428571

[gammaloop]
state = "scalar/2p3L/state"
integration_workspace = "scalar/2p3L/state/integration_workspace"

[integration_target]
real_mean = 5.26647e-6
