run_name = "scalar@2p4L"
output_dir = "scalar/2p4L"
templates = [
    "settings/scalar/base",
    "settings/templates/flow/size9",
    "settings/templates/madnis_bins/size1",
    "settings/templates/transformer/size4",
]

[graph]
momtrop_edge_weight = 0.7777777777777

[gammaloop]
state = "scalar/2p4L/state"
integration_workspace = "scalar/2p4L/state/integration_workspace"
get_target_from_gammaloop = false

[integration_target]
imag_mean = 8.36515e-8

[integrator.madnis]
batch_size = 20000
learning_rate = 4e-4

[layered_integrand]
integrand_type = "gammaloop"
training_phase = "imag"
n_cores = 32
use_f128 = true
