run_name = "scalar@triangle"
output_dir = "scalar/3p1L"
templates = [
    "settings/scalar/base",
    "settings/templates/flow/size7",
    "settings/templates/madnis_bins/size1",
    "settings/templates/transformer/size4",
]

[graph]
momtrop_edge_weight = 0.83333333333

[gammaloop]
state = "scalar/3p1L/state"
integration_workspace = "scalar/3p1L/state/integration_workspace"
get_target_from_gammaloop = true
prefer_gammaloop_over_target = true

[integration_target]
real_central_value = 9.76546e-5
