run_name = "scalar@4p4L"
output_dir = "scalar/4p4L"
templates = [
    "settings/scalar/base",
    "settings/templates/flow/size9",
    "settings/templates/madnis_bins/size1",
    "settings/templates/transformer/size4",
]

[graph]
momtrop_edge_weight = 0.75

[gammaloop]
state = "scalar/4p4L/state"
integration_workspace = "scalar/4p4L/state/integration_workspace"

[integration_target]
real_mean = 2.6919e-14
