run_name = "scalar box"
output_dir = "scalar/4p1L"
templates = [
    "settings/templates/flow/size7",
    "settings/templates/madnis_bins/size1",
    "settings/templates/transformer/size4",
]

[gammaloop_state]
state = "scalar/4p1L/state"
integration_workspace = "scalar/4p1L/state/integration_workspace"
get_target_from_gammaloop = true # If false, will always use [integration_target]
prefer_gammaloop_over_target = true

[layered_integrator]
integrator_type = "madnis"

[integrator.madnis]
batch_size = 2048

[layered_integrand]
integrand_type = "gammaloop"
training_phase = "real"
n_cores = 32

[scripts.sampler_comp]
n_training_steps = 500
n_samples = 100000
n_samples_after_training = 1000000
