run_name = "scalar@box"
output_dir = "scalar/4p1L"
templates = [
    "settings/scalar/base",
    "settings/templates/flow/size7",
    "settings/templates/madnis_bins/size1",
    "settings/templates/transformer/size4",
]

[gammaloop]
state = "scalar/4p1L/state"
integration_workspace = "scalar/4p1L/state/integration_workspace"
get_target_from_gammaloop = true
prefer_gammaloop_over_target = true
