run_name = "scalar@6p2L"
output_dir = "scalar/6p2L"
templates = [
    "settings/scalar/base",
    "settings/templates/flow/size7",
    "settings/templates/madnis_bins/size1",
    "settings/templates/transformer/size4",
]

[graph]
momtrop_edge_weight = 0.55555555555

[gammaloop]
state = "scalar/6p2L/state"
integration_workspace = "scalar/6p2L/state/integration_workspace"

[integration_target]
real_mean = 1.1339e-4
real_error = 5e-8
