run_name = "sunrise@summed"
output_dir = "sunrise/lmb_summed"
templates = [
    "settings/vacuum_graphs/sunrise/base",
    "settings/templates/transformer/size3",
    "settings/templates/flow/size9",
    "settings/templates/madnis_bins/size2",
]

[layered_integrand]
sum_channels = true

[integrator.madnis]
# loss_type = "variance"
loss_type = "kl_divergence"
# scheduler_type = "linear"
batch_size = 10_000
learning_rate = 1e-3

# [integrator.madnis.loss_kwargs]
# type = "kl_divergence"
# T_max = 1000
# threshold = 0.0
# exponent = 0.2

[integrator.madnis.flow_kwargs]
bins = 10
min_bin_width = 2e-3
min_bin_height = 1e-6
min_bin_derivative = 1e-8

[layered_parameterisation.layer_0]
parameterisation_type = "rkaapo"
# chem potential [3.141592653589793, 3.141592653589793, 0.0]
# no chem potential [0.0, 0.0, 0.0]
mu = [3.141592653589793, 3.141592653589793, 0.0]
a = 0.9
b = 1.0

[layered_parameterisation.layer_1]
parameterisation_type = "mc_layer"
subtype = "fermi"
ose_exponent = 5.0
fermi_exponent = 0.8

# Parameters used in the tprog subcommand
[scripts.sampler_comp]
n_training_steps = 500
n_samples = 1_000_000
nitn = 10
# Number of samples drawn after the training to compute the final result
n_samples_after_training = 10_000_000
# Training steps between callback of loss to console
n_log = 20
# Training steps between drawing n_samples samples to calculate the rel. std. (rsd)
# Will also output the result +- error and rsd to console
n_plot_snapshot = 100
# Training steps between plotting the loss
n_plot_loss = 2

[[scripts.slice_plots.slice]]
origin = [0.85857426, 0.84049926, 0.9980109]
dirs = [0, 1]
grid = [
    {start = 0, stop = 1, num = 1000},
]
[[scripts.slice_plots.slice]]
origin = [0.85857426, 0.84049926, 0.9980109]
dirs = [0, 2]
grid = [
    {start = 0, stop = 1, num = 1000},
]
[[scripts.slice_plots.slice]]
origin = [0.85857426, 0.84049926, 0.9980109]
dirs = [1, 2]
grid = [
    {start = 0, stop = 1, num = 1000},
]
[[scripts.slice_plots.slice]]
origin = [0.22636934, 0.85333083, 0.80928787]
dirs = [0, 1]
grid = [
    {start = 0, stop = 1, num = 1000},
]
