run_name = "sunrise@nopot"
output_dir = "sunrise/nopot"
templates = [
    "settings/vacuum_graphs/sunrise/base",
    "settings/vacuum_graphs/sunrise/optimised",
    "settings/templates/flow/size5",
    "settings/templates/madnis_bins/size2",
    "settings/templates/transformer/size2",
]

[integration_target]
# chem potential 0.0138889
# no chem potential 0.0373264
real_mean = 0.0373264

[layered_parameterisation.layer_0]
parameterisation_type = "rkaapo"
# chem potential [3.141592653589793, 3.141592653589793, 0.0]
# no chem potential [0.0, 0.0, 0.0]
mu = [0.0, 0.0, 0.0]
a = 1.0
b = 1.0

[layered_parameterisation.layer_1]
parameterisation_type = "mc_layer"
subtype = "fermi"
ose_exponent = 4.0
fermi_exponent = 1.0

[layered_integrand]
params = [6.283185307179586, 0.0, 1.0]