run_name = "sunrise"
output_dir = "sunrise"
templates = [
    "settings/vacuum_graphs/sunrise/base",
    "settings/templates/flow/size9",
    "settings/templates/madnis_bins/size1",
    "settings/templates/transformer/size2",
]

[scripts.sampler_comp]
n_training_steps = 400
n_samples = 1000000
nitn = 20
n_samples_after_training = 10000000
n_log = 10
n_plot_snapshot = 20
n_plot_loss = 1

[[scripts.slice_plots.slice]]
origin = [0.44341431, 0.22723927, 0.55458468]
discrete = [1]
dirs = [0, 1]
grid = [
    {start = 0, stop = 1, num = 1000},
    {start = 0, stop = 1, num = 1000},
]
[[scripts.slice_plots.slice]]
origin = [0.84720132, 0.83117505, 0.99961965]
discrete = [1]
dirs = [0, 1]
grid = [
    {start = 0, stop = 1, num = 1000},
    {start = 0, stop = 1, num = 1000},
]
[[scripts.slice_plots.slice]]
origin = [0.84720132, 0.83117505, 0.99961965]
discrete = [1]
dirs = [0, 2]
grid = [
    {start = 0, stop = 1, num = 1000},
    {start = 0, stop = 1, num = 1000},
]
[[scripts.slice_plots.slice]]
origin = [0.84720132, 0.83117505, 0.99961965]
discrete = [1]
dirs = [1, 2]
grid = [
    {start = 0, stop = 1, num = 1000},
    {start = 0, stop = 1, num = 1000},
]
[[scripts.slice_plots.slice]]
origin = [0.95709241, 0.97321720, 0.03780411]
discrete = [2]
dirs = [0, 1]
grid = [
    {start = 0, stop = 1, num = 1000},
    {start = 0, stop = 1, num = 1000},
]
[[scripts.slice_plots.slice]]
origin = [0.84720132, 0.83117505, 0.99961965]
discrete = [1]
dirs = [1]
grid = [
    {start = 0, stop = 1, num = 1000},
]