run_name = "sunrise_nomc_softclipped"
templates = ["settings/vacuum_graphs/sunrise/sunrise_mc"]

[layered_parameterisation.layer_0]
parameterisation_type = "rkaapo"
# chem potential [3.141592653589793, 3.141592653589793, 0.0]
# no chem potential [0.0, 0.0, 0.0]
mu = [3.141592653589793, 3.141592653589793, 0.0]
a = 0.5
b = 1.0

[layered_integrator]
loss_type = "kl_divergence_softclip"
