run_name = "sunrise_optimised"
templates = [
    "settings/vacuum_graphs/sunrise/sunrise_base",
    "settings/templates/flow/size5",
    "settings/templates/madnis_bins/size2",
    "settings/templates/transformer/size2",
]

# Parameters used in the tprog subcommand
[scripts.sampler_comp]
n_training_steps = 2000
n_samples = 1000000
nitn = 10
# Number of samples drawn after the training to compute the final result
n_samples_after_training = 100000000
# Training steps between callback of loss to console
n_log = 20
# Training steps between drawing n_samples samples to calculate the rel. std. (rsd)
# Will also output the result +- error and rsd to console
n_plot_rsd = 100
# Training steps between plotting the loss
n_plot_loss = 2
