run_name = "sunrise_mc_vary_a"
templates = ["settings/vacuum_graphs/sunrise/sunrise_mc"]

[layered_parameterisation.layer_0]
parameterisation_type = "rkaapo"
# chem potential [3.141592653589793, 3.141592653589793, 0.0]
# no chem potential [0.0, 0.0, 0.0]
mu = [3.141592653589793, 3.141592653589793, 0.0]
a = 0.5
b = 1.0
vary_a = true
a_min = 0.4

[layered_parameterisation.layer_1]
parameterisation_type = "mc_layer"
subtype = "fermi"
ose_exponent = 2.0
fermi_exponent = 0.5
