run_name = "sunrise_nopot_mc"
templates = ["settings/vacuum_graphs/sunrise/sunrise_mc"]

[integration_target]
# chem potential 0.0138889
# no chem potential 0.0373264
real_central_value = 0.0373264

[layered_parameterisation.layer_0]
parameterisation_type = "rkaapo"
# chem potential [3.141592653589793, 3.141592653589793, 0.0]
# no chem potential [0.0, 0.0, 0.0]
mu = [0.0, 0.0, 0.0]
a = 1.0
b = 1.0

[layered_parameterisation.layer_1]
parameterisation_type = "mc_layer"
subtype = "fermi"
ose_exponent = 4.0
fermi_exponent = 1.0

[layered_integrand]
params = [6.283185307179586, 0.0, 1.0]